// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: middleware.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionMiddleware_BeginSaga_FullMethodName         = "/middleware.TransactionMiddleware/BeginSaga"
	TransactionMiddleware_RegisterSagaStep_FullMethodName  = "/middleware.TransactionMiddleware/RegisterSagaStep"
	TransactionMiddleware_ValidateSaga_FullMethodName      = "/middleware.TransactionMiddleware/ValidateSaga"
	TransactionMiddleware_AbortSaga_FullMethodName         = "/middleware.TransactionMiddleware/AbortSaga"
	TransactionMiddleware_GetSagaState_FullMethodName      = "/middleware.TransactionMiddleware/GetSagaState"
	TransactionMiddleware_ReadResource_FullMethodName      = "/middleware.TransactionMiddleware/ReadResource"
	TransactionMiddleware_CommitTransaction_FullMethodName = "/middleware.TransactionMiddleware/CommitTransaction"
)

// TransactionMiddlewareClient is the client API for TransactionMiddleware service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 미들웨어가 제공하는 서비스 정의
type TransactionMiddlewareClient interface {
	// SagaLLM-compatible workflow lifecycle
	BeginSaga(ctx context.Context, in *BeginSagaRequest, opts ...grpc.CallOption) (*SagaResponse, error)
	RegisterSagaStep(ctx context.Context, in *RegisterSagaStepRequest, opts ...grpc.CallOption) (*SagaResponse, error)
	ValidateSaga(ctx context.Context, in *ValidateSagaRequest, opts ...grpc.CallOption) (*SagaResponse, error)
	AbortSaga(ctx context.Context, in *AbortSagaRequest, opts ...grpc.CallOption) (*SagaResponse, error)
	GetSagaState(ctx context.Context, in *GetSagaStateRequest, opts ...grpc.CallOption) (*SagaState, error)
	// Phase 1: 자원 조회 (QCFuse 기반 캐시 융합 대상)
	ReadResource(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// Phase 3: 트랜잭션 커밋 요청 (ATCC 기반 비용 인지 제어 대상)
	CommitTransaction(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
}

type transactionMiddlewareClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionMiddlewareClient(cc grpc.ClientConnInterface) TransactionMiddlewareClient {
	return &transactionMiddlewareClient{cc}
}

func (c *transactionMiddlewareClient) BeginSaga(ctx context.Context, in *BeginSagaRequest, opts ...grpc.CallOption) (*SagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SagaResponse)
	err := c.cc.Invoke(ctx, TransactionMiddleware_BeginSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionMiddlewareClient) RegisterSagaStep(ctx context.Context, in *RegisterSagaStepRequest, opts ...grpc.CallOption) (*SagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SagaResponse)
	err := c.cc.Invoke(ctx, TransactionMiddleware_RegisterSagaStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionMiddlewareClient) ValidateSaga(ctx context.Context, in *ValidateSagaRequest, opts ...grpc.CallOption) (*SagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SagaResponse)
	err := c.cc.Invoke(ctx, TransactionMiddleware_ValidateSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionMiddlewareClient) AbortSaga(ctx context.Context, in *AbortSagaRequest, opts ...grpc.CallOption) (*SagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SagaResponse)
	err := c.cc.Invoke(ctx, TransactionMiddleware_AbortSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionMiddlewareClient) GetSagaState(ctx context.Context, in *GetSagaStateRequest, opts ...grpc.CallOption) (*SagaState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SagaState)
	err := c.cc.Invoke(ctx, TransactionMiddleware_GetSagaState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionMiddlewareClient) ReadResource(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, TransactionMiddleware_ReadResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionMiddlewareClient) CommitTransaction(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, TransactionMiddleware_CommitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionMiddlewareServer is the server API for TransactionMiddleware service.
// All implementations must embed UnimplementedTransactionMiddlewareServer
// for forward compatibility.
//
// 미들웨어가 제공하는 서비스 정의
type TransactionMiddlewareServer interface {
	// SagaLLM-compatible workflow lifecycle
	BeginSaga(context.Context, *BeginSagaRequest) (*SagaResponse, error)
	RegisterSagaStep(context.Context, *RegisterSagaStepRequest) (*SagaResponse, error)
	ValidateSaga(context.Context, *ValidateSagaRequest) (*SagaResponse, error)
	AbortSaga(context.Context, *AbortSagaRequest) (*SagaResponse, error)
	GetSagaState(context.Context, *GetSagaStateRequest) (*SagaState, error)
	// Phase 1: 자원 조회 (QCFuse 기반 캐시 융합 대상)
	ReadResource(context.Context, *ReadRequest) (*ReadResponse, error)
	// Phase 3: 트랜잭션 커밋 요청 (ATCC 기반 비용 인지 제어 대상)
	CommitTransaction(context.Context, *CommitRequest) (*CommitResponse, error)
	mustEmbedUnimplementedTransactionMiddlewareServer()
}

// UnimplementedTransactionMiddlewareServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionMiddlewareServer struct{}

func (UnimplementedTransactionMiddlewareServer) BeginSaga(context.Context, *BeginSagaRequest) (*SagaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginSaga not implemented")
}
func (UnimplementedTransactionMiddlewareServer) RegisterSagaStep(context.Context, *RegisterSagaStepRequest) (*SagaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSagaStep not implemented")
}
func (UnimplementedTransactionMiddlewareServer) ValidateSaga(context.Context, *ValidateSagaRequest) (*SagaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSaga not implemented")
}
func (UnimplementedTransactionMiddlewareServer) AbortSaga(context.Context, *AbortSagaRequest) (*SagaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortSaga not implemented")
}
func (UnimplementedTransactionMiddlewareServer) GetSagaState(context.Context, *GetSagaStateRequest) (*SagaState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSagaState not implemented")
}
func (UnimplementedTransactionMiddlewareServer) ReadResource(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadResource not implemented")
}
func (UnimplementedTransactionMiddlewareServer) CommitTransaction(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitTransaction not implemented")
}
func (UnimplementedTransactionMiddlewareServer) mustEmbedUnimplementedTransactionMiddlewareServer() {}
func (UnimplementedTransactionMiddlewareServer) testEmbeddedByValue()                               {}

// UnsafeTransactionMiddlewareServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionMiddlewareServer will
// result in compilation errors.
type UnsafeTransactionMiddlewareServer interface {
	mustEmbedUnimplementedTransactionMiddlewareServer()
}

func RegisterTransactionMiddlewareServer(s grpc.ServiceRegistrar, srv TransactionMiddlewareServer) {
	// If the following call pancis, it indicates UnimplementedTransactionMiddlewareServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionMiddleware_ServiceDesc, srv)
}

func _TransactionMiddleware_BeginSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionMiddlewareServer).BeginSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionMiddleware_BeginSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionMiddlewareServer).BeginSaga(ctx, req.(*BeginSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionMiddleware_RegisterSagaStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSagaStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionMiddlewareServer).RegisterSagaStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionMiddleware_RegisterSagaStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionMiddlewareServer).RegisterSagaStep(ctx, req.(*RegisterSagaStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionMiddleware_ValidateSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionMiddlewareServer).ValidateSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionMiddleware_ValidateSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionMiddlewareServer).ValidateSaga(ctx, req.(*ValidateSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionMiddleware_AbortSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionMiddlewareServer).AbortSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionMiddleware_AbortSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionMiddlewareServer).AbortSaga(ctx, req.(*AbortSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionMiddleware_GetSagaState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSagaStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionMiddlewareServer).GetSagaState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionMiddleware_GetSagaState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionMiddlewareServer).GetSagaState(ctx, req.(*GetSagaStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionMiddleware_ReadResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionMiddlewareServer).ReadResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionMiddleware_ReadResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionMiddlewareServer).ReadResource(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionMiddleware_CommitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionMiddlewareServer).CommitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionMiddleware_CommitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionMiddlewareServer).CommitTransaction(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionMiddleware_ServiceDesc is the grpc.ServiceDesc for TransactionMiddleware service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionMiddleware_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "middleware.TransactionMiddleware",
	HandlerType: (*TransactionMiddlewareServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginSaga",
			Handler:    _TransactionMiddleware_BeginSaga_Handler,
		},
		{
			MethodName: "RegisterSagaStep",
			Handler:    _TransactionMiddleware_RegisterSagaStep_Handler,
		},
		{
			MethodName: "ValidateSaga",
			Handler:    _TransactionMiddleware_ValidateSaga_Handler,
		},
		{
			MethodName: "AbortSaga",
			Handler:    _TransactionMiddleware_AbortSaga_Handler,
		},
		{
			MethodName: "GetSagaState",
			Handler:    _TransactionMiddleware_GetSagaState_Handler,
		},
		{
			MethodName: "ReadResource",
			Handler:    _TransactionMiddleware_ReadResource_Handler,
		},
		{
			MethodName: "CommitTransaction",
			Handler:    _TransactionMiddleware_CommitTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "middleware.proto",
}
