// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: middleware.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 1. 조회 요청 메시지 (에이전트 -> 미들웨어)
type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`          // 요청하는 에이전트의 고유 ID
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"` // 조회할 자원 ID (예: "flight_ticket_A")
	Intent        string                 `protobuf:"bytes,3,opt,name=intent,proto3" json:"intent,omitempty"`                           // 조회의 목적 문맥 (QCFuse의 앵커 추출에 활용될 수 있음)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_middleware_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_middleware_proto_rawDescGZIP(), []int{0}
}

func (x *ReadRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReadRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ReadRequest) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

// 2. 조회 응답 메시지 (미들웨어 -> 에이전트)
type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`       // 캐싱 또는 DB에서 읽어온 데이터
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 상태 메시지 (예: "캐시 적중" 또는 "DB 조회 완료")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_middleware_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_middleware_proto_rawDescGZIP(), []int{1}
}

func (x *ReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ReadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 3. 커밋 요청 메시지 (에이전트 -> 미들웨어)
type CommitRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AgentId     string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`              // 에이전트 고유 ID
	ResourceId  string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`     // 수정/구매할 자원 ID
	ActionValue int32                  `protobuf:"varint,3,opt,name=action_value,json=actionValue,proto3" json:"action_value,omitempty"` // 수행할 액션 (예: 재고 1개 차감)
	// ATCC 매몰 비용(Sunk Cost) 산정을 위한 데이터
	AccumulatedTokens   int32   `protobuf:"varint,4,opt,name=accumulated_tokens,json=accumulatedTokens,proto3" json:"accumulated_tokens,omitempty"`          // 에이전트가 현재까지 소모한 누적 LLM 토큰 수
	InferenceLatencySec float32 `protobuf:"fixed32,5,opt,name=inference_latency_sec,json=inferenceLatencySec,proto3" json:"inference_latency_sec,omitempty"` // LLM 추론에 소요된 대기 시간(초)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_middleware_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_middleware_proto_rawDescGZIP(), []int{2}
}

func (x *CommitRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommitRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CommitRequest) GetActionValue() int32 {
	if x != nil {
		return x.ActionValue
	}
	return 0
}

func (x *CommitRequest) GetAccumulatedTokens() int32 {
	if x != nil {
		return x.AccumulatedTokens
	}
	return 0
}

func (x *CommitRequest) GetInferenceLatencySec() float32 {
	if x != nil {
		return x.InferenceLatencySec
	}
	return 0
}

// 4. 커밋 응답 메시지 (미들웨어 -> 에이전트)
type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                  // 커밋 성공 여부 (충돌 시 패배하면 false)
	IsRolledBack  bool                   `protobuf:"varint,2,opt,name=is_rolled_back,json=isRolledBack,proto3" json:"is_rolled_back,omitempty"`  // Saga 코디네이터에 의해 롤백되었는지 여부
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                   // 원인 메시지 (예: "비용이 낮아 롤백됨")
	SavedCostUsd  float32                `protobuf:"fixed32,4,opt,name=saved_cost_usd,json=savedCostUsd,proto3" json:"saved_cost_usd,omitempty"` // 방어해 낸 매몰 비용 가치 (정량적 지표용)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_middleware_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_middleware_proto_rawDescGZIP(), []int{3}
}

func (x *CommitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitResponse) GetIsRolledBack() bool {
	if x != nil {
		return x.IsRolledBack
	}
	return false
}

func (x *CommitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitResponse) GetSavedCostUsd() float32 {
	if x != nil {
		return x.SavedCostUsd
	}
	return 0
}

var File_middleware_proto protoreflect.FileDescriptor

const file_middleware_proto_rawDesc = "" +
	"\n" +
	"\x10middleware.proto\x12\n" +
	"middleware\"a\n" +
	"\vReadRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06intent\x18\x03 \x01(\tR\x06intent\"V\n" +
	"\fReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xd1\x01\n" +
	"\rCommitRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\faction_value\x18\x03 \x01(\x05R\vactionValue\x12-\n" +
	"\x12accumulated_tokens\x18\x04 \x01(\x05R\x11accumulatedTokens\x122\n" +
	"\x15inference_latency_sec\x18\x05 \x01(\x02R\x13inferenceLatencySec\"\x90\x01\n" +
	"\x0eCommitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\x0eis_rolled_back\x18\x02 \x01(\bR\fisRolledBack\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12$\n" +
	"\x0esaved_cost_usd\x18\x04 \x01(\x02R\fsavedCostUsd2\xa6\x01\n" +
	"\x15TransactionMiddleware\x12A\n" +
	"\fReadResource\x12\x17.middleware.ReadRequest\x1a\x18.middleware.ReadResponse\x12J\n" +
	"\x11CommitTransaction\x12\x19.middleware.CommitRequest\x1a\x1a.middleware.CommitResponseB$Z\"agenic-middleware/middleware-go/pbb\x06proto3"

var (
	file_middleware_proto_rawDescOnce sync.Once
	file_middleware_proto_rawDescData []byte
)

func file_middleware_proto_rawDescGZIP() []byte {
	file_middleware_proto_rawDescOnce.Do(func() {
		file_middleware_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_middleware_proto_rawDesc), len(file_middleware_proto_rawDesc)))
	})
	return file_middleware_proto_rawDescData
}

var file_middleware_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_middleware_proto_goTypes = []any{
	(*ReadRequest)(nil),    // 0: middleware.ReadRequest
	(*ReadResponse)(nil),   // 1: middleware.ReadResponse
	(*CommitRequest)(nil),  // 2: middleware.CommitRequest
	(*CommitResponse)(nil), // 3: middleware.CommitResponse
}
var file_middleware_proto_depIdxs = []int32{
	0, // 0: middleware.TransactionMiddleware.ReadResource:input_type -> middleware.ReadRequest
	2, // 1: middleware.TransactionMiddleware.CommitTransaction:input_type -> middleware.CommitRequest
	1, // 2: middleware.TransactionMiddleware.ReadResource:output_type -> middleware.ReadResponse
	3, // 3: middleware.TransactionMiddleware.CommitTransaction:output_type -> middleware.CommitResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_middleware_proto_init() }
func file_middleware_proto_init() {
	if File_middleware_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_middleware_proto_rawDesc), len(file_middleware_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_middleware_proto_goTypes,
		DependencyIndexes: file_middleware_proto_depIdxs,
		MessageInfos:      file_middleware_proto_msgTypes,
	}.Build()
	File_middleware_proto = out.File
	file_middleware_proto_goTypes = nil
	file_middleware_proto_depIdxs = nil
}
