# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: middleware.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'middleware.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10middleware.proto\x12\nmiddleware\"D\n\x0bReadRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x13\n\x0bresource_id\x18\x02 \x01(\t\x12\x0e\n\x06intent\x18\x03 \x01(\t\">\n\x0cReadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x87\x01\n\rCommitRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x13\n\x0bresource_id\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63tion_value\x18\x03 \x01(\x05\x12\x1a\n\x12\x61\x63\x63umulated_tokens\x18\x04 \x01(\x05\x12\x1d\n\x15inference_latency_sec\x18\x05 \x01(\x02\"b\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0eis_rolled_back\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x16\n\x0esaved_cost_usd\x18\x04 \x01(\x02\x32\xa6\x01\n\x15TransactionMiddleware\x12\x41\n\x0cReadResource\x12\x17.middleware.ReadRequest\x1a\x18.middleware.ReadResponse\x12J\n\x11\x43ommitTransaction\x12\x19.middleware.CommitRequest\x1a\x1a.middleware.CommitResponseB$Z\"agenic-middleware/middleware-go/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'middleware_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"agenic-middleware/middleware-go/pb'
  _globals['_READREQUEST']._serialized_start=32
  _globals['_READREQUEST']._serialized_end=100
  _globals['_READRESPONSE']._serialized_start=102
  _globals['_READRESPONSE']._serialized_end=164
  _globals['_COMMITREQUEST']._serialized_start=167
  _globals['_COMMITREQUEST']._serialized_end=302
  _globals['_COMMITRESPONSE']._serialized_start=304
  _globals['_COMMITRESPONSE']._serialized_end=402
  _globals['_TRANSACTIONMIDDLEWARE']._serialized_start=405
  _globals['_TRANSACTIONMIDDLEWARE']._serialized_end=571
# @@protoc_insertion_point(module_scope)
