# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import middleware_pb2 as middleware__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in middleware_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransactionMiddlewareStub(object):
    """미들웨어가 제공하는 서비스 정의
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadResource = channel.unary_unary(
                '/middleware.TransactionMiddleware/ReadResource',
                request_serializer=middleware__pb2.ReadRequest.SerializeToString,
                response_deserializer=middleware__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.CommitTransaction = channel.unary_unary(
                '/middleware.TransactionMiddleware/CommitTransaction',
                request_serializer=middleware__pb2.CommitRequest.SerializeToString,
                response_deserializer=middleware__pb2.CommitResponse.FromString,
                _registered_method=True)


class TransactionMiddlewareServicer(object):
    """미들웨어가 제공하는 서비스 정의
    """

    def ReadResource(self, request, context):
        """Phase 1: 자원 조회 (QCFuse 기반 캐시 융합 대상)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTransaction(self, request, context):
        """Phase 3: 트랜잭션 커밋 요청 (ATCC 기반 비용 인지 제어 대상)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionMiddlewareServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadResource,
                    request_deserializer=middleware__pb2.ReadRequest.FromString,
                    response_serializer=middleware__pb2.ReadResponse.SerializeToString,
            ),
            'CommitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTransaction,
                    request_deserializer=middleware__pb2.CommitRequest.FromString,
                    response_serializer=middleware__pb2.CommitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'middleware.TransactionMiddleware', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('middleware.TransactionMiddleware', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionMiddleware(object):
    """미들웨어가 제공하는 서비스 정의
    """

    @staticmethod
    def ReadResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/middleware.TransactionMiddleware/ReadResource',
            middleware__pb2.ReadRequest.SerializeToString,
            middleware__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/middleware.TransactionMiddleware/CommitTransaction',
            middleware__pb2.CommitRequest.SerializeToString,
            middleware__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
